---
- hosts: ubuntu
  become: true
  gather_facts: true
  tasks:
    - name: "Install nginx"
      ansible.builtin.apt:
        name: nginx=1.18.0-0ubuntu1.2
        state: fixed
        update_cache: yes

    - name: "Copy nginx config"
      ansible.builtin.copy:
        src: etc/nginx/default.conf
        dest: /etc/nginx/conf.d/default.conf

    - name: "Copy wa-vagrant.html page"
      ansible.builtin.copy:
        src: files/html/wa-vagrant.html
        dest: /var/www/html
        owner: vagrant
        group: vagrant
        mode: 0644
