---
- hosts: ubuntu
  become: true
  gather_facts: false
  vars_files:
    - vars/default.yml

  tasks:
    - name: "Add repository ondrej/php"
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

    - name: "Install php"
      ansible.builtin.apt:
        name: "php{{ php_version }}-fpm"
        state: fixed
        update_cache: yes

    - name: "Install php extensions"
      ansible.builtin.apt:
        name: "php{{ php_version }}-{{ item }}"
        update_cache: yes
      with_items:
       - mysql
       - curl

    - name: "Copy www config"
      ansible.builtin.copy:
        src: files/etc/php/fpm/www.conf
        dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
      notify: "reload php-fpm"

    - name: "Copy php info page"
      ansible.builtin.copy:
        src: files/www/info.php
        dest: /var/www/html
        owner: vagrant
        group: vagrant
        mode: 0644

  handlers:
    - name: "reload php-fpm"
      ansible.builtin.service:
        name: "php{{ php_version }}-fpm"
        state: reloaded
