---
- hosts: ubuntu
  become: true
  gather_facts: true
  tasks:
    - name: "Install nginx"
      ansible.builtin.apt:
        name: nginx=1.18.0-0ubuntu1.2
        state: fixed
        update_cache: yes
    # - name: "Copy nginx config"
    #   ansible.builtin.apt:
    #     src: etc/nginx/default.conf
    #     dest: /etc/nginx/sites-available/default.conf
