---
- hosts: ubuntu
  become: true
  gather_facts: false
  vars_files:
    - vars/default.yml

  tasks:
    - name: "Install nginx"
      ansible.builtin.apt:
        name: "nginx={{ nginx_version }}"
        state: fixed
        update_cache: yes

    - name: "Copy nginx config"
      ansible.builtin.template:
        src: files/etc/nginx/default.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: "Enable new site"
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: "reload nginx"

    - name: "Copy index.html page"
      ansible.builtin.template:
        src: files/www/html/index.html.j2
        dest: /var/www/html/index.html
        owner: vagrant
        group: vagrant
        mode: 0644

  handlers:
    - name: "reload nginx"
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: "restart nginx"
      ansible.builtin.service:
        name: nginx
        state: restarted
