---
- hosts: ubuntu
  become: true
  gather_facts: true
  tasks:
    - name: "Add repository ondrej/php"
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

    - name: "Install php"
      ansible.builtin.apt:
        name: php8.1
        state: fixed
        update_cache: yes

    - name: "Install php extensions"
      ansible.builtin.apt:
        name: "php8.1-{{ item }}"
        update_cache: yes
      with_items:
       - fpm
       - mysql
       - curl

    - name: "Copy php-fpm config"
      ansible.builtin.copy:
        src: etc/php/fpm/php.ini
        dest: /etc/php/8.1/fpm/php.ini
      notify: "reload php-fpm"

  handlers:
    - name: "reload php-fpm"
      ansible.builtin.service:
        name: php8.1-fpm
        state: reloaded
