---
- hosts: all
  become: true
  become_user: root
  remote_user: vagrant
  gather_facts: false
  tasks:
    - name: "SSH check"
      become: false
      wait_for:
        port: 22
        delay: 5
        connect_timeout: 5
        timeout: 360
        host: "{{ ansible_host }}"
      delegate_to: localhost